.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "PMS-LINUX" "1"  "February  22, 2011" "" ""
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pms-linux \- PS3 Media Server for Linux
.SH SYNOPSIS
.B pms-linux
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the PS3 Media Server for Linux.
\fBpms-linux\fR is a DLNA compliant Upnp Media Server for the PS3, written in Java, with the purpose of streaming or transcoding any kind of media files, with minimum configuration. It's backed up with the powerful Mplayer/FFmpeg packages.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.SH NOTES
You can start pms-linux manually into a terminal or from the menu icon.
.br
You can also the start it from /etc/rc.d/pms-linux.
.br
The default configuration file used is $HOME/.PMS.conf
.br
You can specify another configuration file to use with the \fB-c\fP or \fB--conf\fP option.
.br
But if you start pms-linux from the rc.d script (/etc/rc.d/pms-linux start), the program will use /etc/pms-linux/PMS.conf.
.br
.SH OPTIONS
Not all options are documented yet.
.sp 2
.IP "\fB-c\fR, \fB--conf \fIconfFile\fR"
Example: pms-linux \-c /etc/myOtherPMS.conf
.br
\fBImportant:\fR
.br
   If an error occurs, pms-linux will use default configuration file $HOME/.PMS.conf.
.br
   If you use the GUI for saving your configuration, the modifications are stored in $HOME/.PMS.conf, not in the conf file specified with the \-c option.
.sp
.IP "\fBconsole\fR"
Disables the GUI environment.
.sp 2
.SH SEE ALSO
.BR mplayer (1),
.BR mencoder (1),
.BR ffmpeg (1),
.BR vlc (1),
.BR dcraw (1)
.br
.SH AUTHOR
pms-linux was written by shagrath <ps3mediaserver@gmail.com>.
.PP
This manual page was written by Papa Issa DIAKHATE aka paissad <paissad@gmail.com> (and may be used by others).
.br
Special thanks to Roger R. Moore <roger.r.moore@bigfoot.com> who made some modifications for this manpage.
