#!/bin/bash

# Copyright 2010, Papa Issa DIAKHATE (paissad), Montpellier, FRANCE. 
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Requirements:
# Suggests:

PACKAGER_ID=${PACKAGER_ID:-$USER}
PACKAGER=${PACKAGER:-$USER@$(hostname)}
DATE=$(LC_ALL=C date +%d-%b-%Y)

PRGNAM=${PRGNAM:-denyhosts}
SRCNAM=${SRCNAM:-DenyHosts}
VERSION=${VERSION:-2.6}
ARCH=${ARCH:-$(uname -m)}
BUILD=${BUILD:-1}
CWD=${CWD:-`pwd`}
TMP=${TMP:-/tmp/SBp}
PKG=${PKG:-$TMP/package-$PRGNAM}
OUTPUT=${OUTPUT:-/tmp}
EXT=${EXT:-tar.gz}
URL=${URL:-http://sourceforge.net/projects/denyhosts/files/denyhosts/2.6/$SRCNAM-$VERSION.$EXT/download}
TAG=${TAG:-_paissad}
PKGTYPE=${PKGTYPE:-tgz}
PREFIX=${PREFIX:-"/usr"}
NUMJOBS=${NUMJOBS:-}
DOCS=${DOCS:-"CREDITS WHISHLIST ABOUT-NLS AUTHORS COPYING LICENSE LICENSE.txt \
CHANGELOG ChangeLog CHANGELOG.txt  HACKING INSTALL INSTALL.txt MAINTAINERS NEWS \
ReadMe README README.txt THANKS TODO RELEASE UPGRADING FAQ HELP"}

set -e

txtred=$'\e[0;31m' # Red
txtgrn=$'\e[0;32m' # Green
txtylw=$'\e[0;33m' # Yellow
txtblu=$'\e[0;34m' # Blue
txtpur=$'\e[0;35m' # Purple
txtcyn=$'\e[0;36m' # Cyan
txtrst=$'\e[0m'    # Text Reset

frame()
{
    WIDTH=78
    STARS="++----------------------------------------------------------------------------+"
    SPACES="                                                                               "
    printf "%s\n" "${STARS:1:$WIDTH}"
    while read line ; do
        HALF="${SPACES:1:$((($WIDTH-${#line})/2))}"
        LINE="$HALF$line$SPACES"
        printf "+%s+\n" "${LINE:1:$(($WIDTH-2))}"
    done
    printf "%s\n" "${STARS:1:$WIDTH}"
}
introduce(){
    echo -e "$txtgrn"; printf "$1\n" | frame; echo -e "$txtrst \c "; sleep 2;
}
conclude(){
    echo -e "${txtgrn}\n# $1 \n${txtrst}"; sleep 2;
}
shellout(){
    echo -e "${txtred}Error:${txtrst} $1 ${txtcyn}(exit status -> $?)${txtrst}"; exit 1;
}
warnout(){
    echo -e "${txtylw}Warning:${txtrst} $1"; sleep 3;
}
if [ ! -r ${SRCNAM}-${VERSION}.$EXT ]; then
    introduce "Start downloading ${SRCNAM}-${VERSION}.$EXT" 
    wget "$URL" || shellout "Downloading ${SRCNAM}-${VERSION}.$EXT"
    conclude "Download of ${SRCNAM}-${VERSION}.$EXT finished successfully !"
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP || exit 1
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/${SRCNAM}-${VERSION}.$EXT \
|| shellout "Extracting ${SRCNAM}-${VERSION}.$EXT"

# Download of the source !
introduce "Start SlackBuild $PRGNAM-$VERSION"
test -d $PRGNAM-$VERSION || \
mv -v ${SRCNAM}-${VERSION} $PRGNAM-$VERSION
cd $TMP/$PRGNAM-$VERSION

chown -R root:root .
find . \
\( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
-exec chmod 755 {} \; -o \
\( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o \
-perm 400 \) -exec chmod 644 {} \;

python setup.py install --root $PKG \
|| shellout "python setup.py install failed."

mkdir -p $PKG/usr/sbin
mkdir -p $PKG/etc/{rc.d,logrotate.d}
mkdir -p $PKG/var/log/denyhosts

# Let's change the default name & place of denyhosts.py
mv $PKG/usr/bin/denyhosts.py $PKG/usr/sbin/denyhosts || exit 1

# Let's copy the main conf file in /etc
install -m 0644 $TMP/$PRGNAM-$VERSION/denyhosts.cfg-dist $PKG/etc/denyhosts.conf.new || exit 1

# manpage & zip it !
install -D -m 0644 $CWD/denyhosts.8 $PKG/usr/man/man8/denyhosts.8 || exit 1
gzip -9 $PKG/usr/man/man8/denyhosts.8 || exit 1
# rc.sript
install -m 0755 $TMP/$PRGNAM-$VERSION/daemon-control-dist $PKG/etc/rc.d/rc.denyhosts.new || exit 1
#
# 1°) We change the occurences of denyhosts.py to denyhosts in rc.denyhosts.new
# 2°) We change the default value of $DENYHOSTS_BIN
# 3°) We change the default value of $DENYHOSTS_CFG (conf file)
# 4°) We change the default value of $DENYHOSTS_LOCK
sed -i \
-e "s/\(denyhosts\)\.py/\1/g" \
-e "s,\(^DENYHOSTS_BIN *= *\"\).*,\1/usr/sbin/denyhosts\"," \
-e "s,\(^DENYHOSTS_CFG *= *\"\).*,\1/etc/denyhosts.conf\"," \
-e "s,\(^DENYHOSTS_LOCK *= *\"\).*,\1/var/lock/denyhosts\"," \
$PKG/etc/rc.d/rc.denyhosts.new \
|| shellout "Changing default values in rc.denyhosts.new failed."

# install logrotate file
install -m 0644 $CWD/denyhosts.logrotate $PKG/etc/logrotate.d/denyhosts.new || exit 1

# Installation of slack-desc
mkdir -p $PKG/install 
( test -r $CWD/slack-desc && \
cat $CWD/slack-desc > $PKG/install/slack-desc ) || \
cat << EODESC > $PKG/install/slack-desc
# HOW TO EDIT THIS FILE:            
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|' 
# on the right side marks the last column you can put a character in.  You
# must
# make exactly 11 lines for the formatting to be correct.  It's also           
# customary to leave one space after the ':'.                                  

         |-----handy-ruler----------------------------------------------------|
denyhosts:                                   ( denyhosts )
denyhosts:
denyhosts: DenyHosts is a script intended to be run by Linux system 
denyhosts: administrators to help thwart SSH server attacks (also known as
denyhosts: dictionary based attacks and brute force attacks).
denyhosts: 
denyhosts: 
denyhosts: Homepage: http://denyhosts.sourceforge.net
denyhosts: 
denyhosts: Packager: _PACKAGER on _BUILD_DATE
denyhosts:
EODESC

# Install a doinst.sh, if it exists
if [ -r $CWD/doinst.sh ]; then
   cat $CWD/doinst.sh > $PKG/install/doinst.sh
fi

# Install the documentation
cd $TMP/$PRGNAM-$VERSION
mkdir -p $PKG/$PREFIX/doc/$PRGNAM-$VERSION
for i in $DOCS ;
do 
  if [ -r $i ]; then
    install -m 644 $i $PKG/$PREFIX/doc/$PRGNAM-$VERSION
  fi
done

mkdir -p  $PKG/$PREFIX/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/$PREFIX/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
chown -R root:root $PKG/usr/doc/$PRGNAM-$VERSION
find $PKG/$PREFIX/doc -type f -exec chmod 0644 {} \;

mkdir -p $PKG/install
test -r $CWD/slack-desc && \
cat $CWD/slack-desc > $PKG/install/slack-desc
# -- finished install docs --

# We change the default values in the slack-desc 
sed -i "s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
${PKG}/install/slack-desc || true

cd $PKG 
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE \
|| shellout "/sbin/makepkg for $PRGNAM-$VERSION failed"

conclude "Done ..."
